# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - LeHandBookExpert

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sampleappaoaichatgpt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0809ffef78bb4f97b882032a942e2dc8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_753f84ddfde8486da60bd9512168dd5f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0809ffef78bb4f97b882032a942e2dc8 }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'LeHandBookExpert'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_63fb98e963224862a405b6135ad40083 }}
        images: 'sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0809ffef78bb4f97b882032a942e2dc8 }}/sample-app-aoai-chatgpt:${{ github.sha }}'